-- QUANTUM operational parity: private legal preferences, owner-only mail logs, anonymous ratings and consent-aware events.


create table if not exists public.qm_user_legal_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  terms_version text,
  terms_accepted_at timestamptz,
  privacy_version text,
  privacy_acknowledged_at timestamptz,
  email_updates_opted_in boolean not null default true,
  email_updates_opted_in_at timestamptz,
  email_updates_opted_out_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint qm_user_legal_preferences_terms_pair_check check (
    (terms_version is null) = (terms_accepted_at is null)
  ),
  constraint qm_user_legal_preferences_privacy_pair_check check (
    (privacy_version is null) = (privacy_acknowledged_at is null)
  )
);

create or replace function public.set_qm_user_legal_preferences_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists qm_user_legal_preferences_set_updated_at on public.qm_user_legal_preferences;
create trigger qm_user_legal_preferences_set_updated_at
before update on public.qm_user_legal_preferences
for each row execute function public.set_qm_user_legal_preferences_updated_at();

alter table public.qm_user_legal_preferences enable row level security;

revoke all on public.qm_user_legal_preferences from anon, authenticated;
grant select, insert, update on public.qm_user_legal_preferences to service_role;


create table if not exists public.qm_email_campaigns (
  id uuid primary key,
  created_at timestamptz not null default timezone('utc', now()),
  created_by uuid not null references auth.users(id) on delete restrict,
  audience_type text not null check (audience_type in ('all_opted_in', 'selected_users')),
  recipient_count integer not null check (recipient_count >= 0),
  subject text not null,
  message text not null,
  cta_label text,
  cta_url text,
  status text not null check (status in ('sending', 'sent', 'partial_failure', 'failed')),
  delivered_count integer not null default 0 check (delivered_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  resend_message_ids jsonb not null default '[]'::jsonb
);

alter table public.qm_email_campaigns enable row level security;

revoke all on public.qm_email_campaigns from anon, authenticated;
grant select, insert, update on public.qm_email_campaigns to service_role;


create table if not exists public.qm_email_recipient_deliveries (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default timezone('utc', now()),
  campaign_id uuid references public.qm_email_campaigns(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  delivery_kind text not null check (delivery_kind in ('campaign', 'return_reminder')),
  idempotency_key text not null unique,
  subject text not null,
  status text not null check (status in ('pending', 'sent', 'failed', 'skipped')),
  reason text,
  resend_message_id text,
  sent_at timestamptz
);

create index if not exists qm_email_recipient_deliveries_user_sent_idx
  on public.qm_email_recipient_deliveries (user_id, sent_at desc);

create index if not exists qm_email_recipient_deliveries_kind_sent_idx
  on public.qm_email_recipient_deliveries (delivery_kind, sent_at desc);

alter table public.qm_email_recipient_deliveries enable row level security;

revoke all on public.qm_email_recipient_deliveries from anon, authenticated;
grant select, insert, update on public.qm_email_recipient_deliveries to service_role;


create table if not exists public.qm_app_ratings (
  id bigint generated by default as identity primary key,
  visitor_hash text not null unique,
  rating smallint not null,
  feedback text,
  feedback_prompt text,
  page_path text,
  visit_count integer not null default 0,
  content_view_count integer not null default 0,
  first_submitted_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint qm_app_ratings_rating_check check (rating between 1 and 5),
  constraint qm_app_ratings_feedback_length_check check (feedback is null or char_length(feedback) <= 600),
  constraint qm_app_ratings_feedback_prompt_check check (
    feedback_prompt is null or feedback_prompt in ('improvement', 'highlight')
  ),
  constraint qm_app_ratings_page_path_length_check check (page_path is null or char_length(page_path) <= 240),
  constraint qm_app_ratings_visit_count_check check (visit_count between 0 and 100000),
  constraint qm_app_ratings_content_view_count_check check (content_view_count between 0 and 100000)
);

create index if not exists qm_app_ratings_updated_at_idx
  on public.qm_app_ratings (updated_at desc);

create index if not exists qm_app_ratings_rating_updated_at_idx
  on public.qm_app_ratings (rating, updated_at desc);

alter table public.qm_app_ratings enable row level security;

revoke all on public.qm_app_ratings from anon, authenticated;
grant select, insert, update, delete on public.qm_app_ratings to service_role;
grant usage, select on sequence public.qm_app_ratings_id_seq to service_role;


create table if not exists public.qm_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null check (char_length(event_name) between 1 and 80),
  page_path text check (page_path is null or char_length(page_path) <= 240),
  properties jsonb not null default '{}'::jsonb check (jsonb_typeof(properties) = 'object'),
  consent_version text not null,
  created_at timestamptz not null default timezone('utc', now())
);
create index if not exists qm_analytics_events_created_idx on public.qm_analytics_events (created_at desc);
create index if not exists qm_analytics_events_name_created_idx on public.qm_analytics_events (event_name, created_at desc);
alter table public.qm_analytics_events enable row level security;
revoke all on public.qm_analytics_events from anon, authenticated;
grant select, insert on public.qm_analytics_events to service_role;

-- Existing RLS event trigger runs as the database owner; it must not be callable through the public RPC surface.
revoke execute on function public.rls_auto_enable() from public;
